[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/wb/*"
  to = "https://api.worldbank.org/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify", Access-Control-Allow-Origin = "https://acts.africa, https://www.acts.africa"}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/wb/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://acts.africa, https://www.acts.africa"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200