@echo off
echo Initializing git repository...
git init
echo Adding .gitignore...
git add .gitignore
echo Adding all files except node_modules...
git add .
echo Committing files...
git commit -m "Initial commit - ACTS.Africa project"
echo Git repository initialized successfully!
pause
